# action.yml
name: 'Send job state to pr'
description: 'This action publish commit statuses for a given SHA. It can be used to publish a workflow result on a pull request.'
author: "jbuettnerbild"
branding:
  color: blue
  icon: anchor
inputs:
  state:
    description: 'The state of the status'
    required: true
    default: 'success'
  target_url:
    description: 'The target URL to associate with this status'
    required: false
  description:
    description: 'A short description of the status'
    required: false
  context:
    description: 'A string label to differentiate this status from the status of other systems. This field is case-insensitive.'
    required: false
    default: 'default'
  repository:
    description: 'The account owner and the repository. The name is not case sensitive. e.g. octocat/Hello-World'
    required: true
  github_token:
    description: 'The github token for authorization'
    required: true
  sha:
    description:  'The sha of the commit'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        PAYLOAD="{\"state\":\"$STATE\",\"target_url\":\"$TARGET_URL\",\"description\":\"$DESCRIPTION\",\"context\":\"$CONTEXT\"}"
        curl -i -X POST -H "Accept: application/vnd.github+json" -H "authorization: Bearer $GITHUB_TOKEN" -d "$PAYLOAD" https://api.github.com/repos/$REPOSITORY/statuses/$SHA
      shell: bash
      env:
        STATE: "${{ inputs.state }}"
        TARGET_URL: "${{ inputs.target_url }}"
        DESCRIPTION: "${{ inputs.description }}"
        CONTEXT: "${{ inputs.context }}"
        REPOSITORY: "${{ inputs.repository }}"
        GITHUB_TOKEN: "${{ inputs.github_token }}"
        SHA: "${{ inputs.sha }}"
